sudo: false
cache: pip
language: python
python:
- 3.6
env:
  matrix:
  - TOXENV=py
  - TOXENV=rst-lint
  - TOXENV=docs
before_install:
- pip install codecov
install:
- pip install tox
script:
- travis_wait 45 tox
after_success:
- tox -e coverage-report
- codecov
notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
deploy:
  user: cthoyt
  password:
    secure: vvKluuq6+bcUO4ZcirPx1eqiXQGuqyxbrvR21DK2jev13CgYkLoEe58yTtsq3NlORE5GlX2dyYRdg+xTC3gh2Los+LCey8nQws+0K3QSE+qhu3rJLHTlL7r+swd6clyaAuEIDlAJwy0QS+2SM1DDiY57Cp2GUNJ8gxWcVlU7kW3dULHi06dz+r4hNbUDShWfZmSeLwKRA3E0w89MXHu0dpmGsv3guvPIFYG/TNp7+KqWDfr+FBwh7X6gNcTQKBI2RLYTynUX7kPpOKcSjSq8QlEE99/Bsijq+IK5v5FkhtT7xw3ypmDGghTXpUSe6hyn4+8bxSQ/LJ+No9ZTUI2+aSDAREFXJIhKGQVFk1yjJh3x5pf/kCfIwzX6uDa8QCTrLdf9OwUlmCeR9lBjx+0IUl2/lWhOGTC+mwCIJ96WUIYLm4Jp4kknssRcqj/yWOrsN7HancllwSt9JF2nfEPq7kpnVRAyTb3qTgMRVvzBjL4fA0R20Bfu4jAqxU0EgfNVsuUZhPa8zjMUJeSqJoTzxLkmg58C5p0gobHilqC407Mig+tokAgvI0g9oJFI4mxbbrdMIsYIr/HLqJDgyp2qFZlu2ng2XrMaX0pVpzWKNpfFvuy+dEBfcxctp/QxTdtyt7JTloHb9hwPyRNkVb6DvFFFDOYQyK6+D9OQgYq42CQ=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: bio2bel/chebi
    branch: master
